import Head from "next/head";
import { FC } from "react";

const Favorites: FC = () => {
  return (
    <>
      <Head>
        <title>Jobored | Favorites</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section>
        <h1>favorites</h1>
      </section>
    </>
  );
};

export default Favorites;
