import Head from "next/head";
import { FC, useEffect } from "react";
import axios from "axios";

const Favorites: FC = () => {
  async function test() {
    const res = await axios.get("https://startup-summer-2023-proxy.onrender.com/2.0/vacancies", {
      headers: {
        "X-Api-App-Id": "v3.r.137440105.399b9c5f19384345afe0ad0339e619e71c66af1d.800f8642a38256679e908c370c44267f705c2909",
        Authorization: localStorage.getItem("Access"),
      },
    });
    // console.log(res.data);
  }

  useEffect(() => {
    // test();
  }, []);
  return (
    <>
      <Head>
        <title>Jobored | Favorites</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section>
        <h1>favorites</h1>
      </section>
    </>
  );
};

export default Favorites;
