import { FC } from "react";
import { Inter } from "next/font/google";
import { LayoutProps } from "@/types";
import Header from "../header";
import Head from "next/head";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const AppLayout: FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={inter.className}>
        <Header />
        {children}
      </div>
    </>
  );
};

export default AppLayout;
